### ISSUE TITLE
Add error handling for person API calls

### ISSUE THREAD

**Issue by leio10** [podemos-info/decidim-module-census_connector#1]
Handle error messages.
Handle connection errors.

**Comment by deivid-rodriguez** [comment]
How should we validate form inputs? I'm thinking of two, maybe complementary, options:

* Duplicate form validations on both sides.
* Keep connector forms validationless and rely on API validations. Add the errors dinamically to the form from the API response.

As an example, currently spanish DNI's validations are only done on the census side, but those errors are not displayed in the form since the errors returned by the API are not added to the form. We can add them, or make the same validation in the connector as well.

I guess the second option would be cleaner and more maintainable.

**Comment by leio10** [comment]
Yes, let's advance with the second option, and in the future we can add an extra validation on decidim side to avoid the extra round-trip.
